/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.pizzalaskuri;

import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author 20128509
 */
public class Pizzalaskuri extends javax.swing.JFrame {

    /**
     * Creates new form Pizzalaskuri
     */
    public Pizzalaskuri() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupKoko = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jradioNormaali = new javax.swing.JRadioButton();
        jradioPerhe = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtHinta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtMaara = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtArea = new javax.swing.JTextArea();
        jchkKinkku = new javax.swing.JCheckBox();
        jchkAnanas = new javax.swing.JCheckBox();
        jchkMeetwursti = new javax.swing.JCheckBox();
        jchkKana = new javax.swing.JCheckBox();
        jchkHerkkusieni = new javax.swing.JCheckBox();
        jchkAurajuusto = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtNormaali = new javax.swing.JTextField();
        jtxtPerhe = new javax.swing.JTextField();
        jtxtYhteensä = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jspnTarkuus = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Pizzalaskuri");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Valitse koko, kappalemäärä ja täytteet, niin ohjelma laskee hinnan pizzalle.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Normaali ja perhepizzanhintaan kuuluu pohja, tomaattikastike ja juusto.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Koko");

        btngroupKoko.add(jradioNormaali);
        jradioNormaali.setText("Normaali hinta €");
        jradioNormaali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioNormaaliActionPerformed(evt);
            }
        });

        btngroupKoko.add(jradioPerhe);
        jradioPerhe.setText("Perhe hinta €");
        jradioPerhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioPerheActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Täytteet");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Hinta");

        jtxtHinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHintaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Määrä");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Tilaa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtxtArea.setColumns(20);
        jtxtArea.setRows(5);
        jScrollPane1.setViewportView(jtxtArea);

        jchkKinkku.setText("Kinkku + 0,75 €");
        jchkKinkku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkKinkkuActionPerformed(evt);
            }
        });

        jchkAnanas.setText("Ananas + 0,50 €");
        jchkAnanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAnanasActionPerformed(evt);
            }
        });

        jchkMeetwursti.setText("Meetwursti + 0,50 €");
        jchkMeetwursti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMeetwurstiActionPerformed(evt);
            }
        });

        jchkKana.setText("Kana + 0,80 €");
        jchkKana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkKanaActionPerformed(evt);
            }
        });

        jchkHerkkusieni.setText("Herkkusieni + 0,50 €");
        jchkHerkkusieni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkHerkkusieniActionPerformed(evt);
            }
        });

        jchkAurajuusto.setText("Aurajuusto + 0,50 €");
        jchkAurajuusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAurajuustoActionPerformed(evt);
            }
        });

        jLabel8.setText("kpl");

        jLabel9.setText("ahinta");

        jLabel10.setText("yhteensä");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Yhteensä:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkKana)
                            .addComponent(jchkAnanas)
                            .addComponent(jchkHerkkusieni)
                            .addComponent(jchkAurajuusto)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addComponent(jtxtHinta, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jchkMeetwursti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jspnTarkuus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jradioPerhe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jchkKinkku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jradioNormaali, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtNormaali, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(jtxtPerhe)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtxtYhteensä, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jradioNormaali)
                        .addComponent(jtxtNormaali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradioPerhe)
                    .addComponent(jtxtPerhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jchkKinkku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkAnanas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkMeetwursti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkKana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkHerkkusieni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkAurajuusto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspnTarkuus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtYhteensä, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchkAurajuustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAurajuustoActionPerformed
        Laskepizzanhinta();
    }//GEN-LAST:event_jchkAurajuustoActionPerformed

    private void jtxtHintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHintaActionPerformed


    }//GEN-LAST:event_jtxtHintaActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //methodin kutsuminen
        Laskepizzanhinta();
        String strmaara = jtxtMaara.getText();
        if (strmaara.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Määrä ei voi olla tyhjä", "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            float maara1 = Float.parseFloat(jtxtMaara.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita, kiitos. virhe: " + e.getMessage(), "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int maara = Integer.parseInt(jtxtMaara.getText());
        double hinta = Double.parseDouble(jtxtHinta.getText());

        jtxtArea.append(maara + " kpl" + "\t" + hinta + " €" + "\t" + hinta * maara + " €" + "\n");

        double yhteensa;

        yhteensa = maara * hinta;
        jtxtYhteensä.setText(String.valueOf(yhteensa));

        double R;
        int tarkuus = (Integer) jspnTarkuus.getValue();
        R = Double.parseDouble(this.jtxtHinta.getText());
        JOptionPane.showInternalMessageDialog(rootPane, "Ympyrän pintaala on:" + String.valueOf(Pyorista(Laskeala(R), tarkuus)));
    }

    static double Laskeala(double R) {
        double A;
        A = 3.14 * R * R;
        return A;
    }

    static BigDecimal Pyorista(double luku, int desimaalit) {
        return BigDecimal.valueOf(luku).setScale(desimaalit, BigDecimal.ROUND_HALF_UP);
    }

    void Laskepizzanhinta() {
        double hinta = 0;

        jradioNormaali.setActionCommand("Normaali");
        jradioPerhe.setActionCommand("Perhe");

        if (btngroupKoko.getSelection().getActionCommand() == "Normaali") {

            if (jtxtNormaali.getText().equals("")) {
                hinta = 5;
                jtxtNormaali.setText("5");
            } else {
                try {
                    hinta = Double.parseDouble(jtxtNormaali.getText());

                } catch (Exception e) {
                    hinta = 5;
                    jtxtNormaali.setText("5");
                }
            }
            jtxtPerhe.setText(" ");
        } else if (btngroupKoko.getSelection().getActionCommand() == "Perhe") {

            if (jtxtPerhe.getText().equals("")) {
                hinta = 9;
                jtxtPerhe.setText("9");
            } else {
                try {
                    hinta = Double.parseDouble(jtxtPerhe.getText());
                } catch (Exception e) {
                    hinta = 9;
                    jtxtPerhe.setText("9");
                }
            }
            jtxtNormaali.setText(" ");
        }

        if (jchkKinkku.isSelected()) {
            hinta = hinta + 0.75;
        }
        if (jchkAnanas.isSelected()) {
            hinta = hinta + 0.50;
        }
        if (jchkMeetwursti.isSelected()) {
            hinta = hinta + 0.50;
        }
        if (jchkKana.isSelected()) {
            hinta = hinta + 0.80;
        }
        if (jchkHerkkusieni.isSelected()) {
            hinta = hinta + 0.50;
        }
        if (jchkAurajuusto.isSelected()) {
            hinta = hinta + 0.50;
        }

        jtxtHinta.setText(String.valueOf(hinta));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jradioNormaaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioNormaaliActionPerformed
        Laskepizzanhinta();
    }//GEN-LAST:event_jradioNormaaliActionPerformed

    private void jradioPerheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioPerheActionPerformed
        Laskepizzanhinta();
    }//GEN-LAST:event_jradioPerheActionPerformed

    private void jchkKinkkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkKinkkuActionPerformed
        Laskepizzanhinta();
    }//GEN-LAST:event_jchkKinkkuActionPerformed

    private void jchkAnanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAnanasActionPerformed
        Laskepizzanhinta();
    }//GEN-LAST:event_jchkAnanasActionPerformed

    private void jchkMeetwurstiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMeetwurstiActionPerformed
        Laskepizzanhinta();
    }//GEN-LAST:event_jchkMeetwurstiActionPerformed

    private void jchkKanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkKanaActionPerformed
        Laskepizzanhinta();
    }//GEN-LAST:event_jchkKanaActionPerformed

    private void jchkHerkkusieniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkHerkkusieniActionPerformed
        Laskepizzanhinta();
    }//GEN-LAST:event_jchkHerkkusieniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzalaskuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzalaskuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzalaskuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzalaskuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzalaskuri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroupKoko;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jchkAnanas;
    private javax.swing.JCheckBox jchkAurajuusto;
    private javax.swing.JCheckBox jchkHerkkusieni;
    private javax.swing.JCheckBox jchkKana;
    private javax.swing.JCheckBox jchkKinkku;
    private javax.swing.JCheckBox jchkMeetwursti;
    private javax.swing.JRadioButton jradioNormaali;
    private javax.swing.JRadioButton jradioPerhe;
    private javax.swing.JSpinner jspnTarkuus;
    private javax.swing.JTextArea jtxtArea;
    private javax.swing.JTextField jtxtHinta;
    private javax.swing.JTextField jtxtMaara;
    private javax.swing.JTextField jtxtNormaali;
    private javax.swing.JTextField jtxtPerhe;
    private javax.swing.JTextField jtxtYhteensä;
    // End of variables declaration//GEN-END:variables
}
